// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['app']['App']['DownloadFile'](arg1);
}

export function DownloadFolder(arg1) {
  return window['go']['app']['App']['DownloadFolder'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function List(arg1) {
  return window['go']['app']['App']['List'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['app']['App']['UploadFile'](arg1);
}

export function UploadFolder(arg1) {
  return window['go']['app']['App']['UploadFolder'](arg1);
}
